name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10.0-beta - 3.10'
        os:
          # Windows Server 2019
          - windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}

      - name: Update pip
        run: python -m pip install -U pip

      - name: Print PATH
        run: Write-Host $Env:Path

      - name: Print PATHEXT
        run: Write-Host $Env:PathExt

      - name: Find make
        run: Get-ChildItem C:\ -recurse -include "make.exe", "make.EXE"

      - name: Show make version
        run: make --version

      - name: Install PyNaCl
        run: pip install pynacl

      - name: PyNaCl info
        run: |
          python -m pip list
          python -m pip show pynacl
