name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python:
          - '3.7'
        os:
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}

      - name: Update pip
        run: python -m pip install -U pip

      - name: Install PyNaCl
        run: pip install pynacl

      - name: PyNaCl info
        run: |
          python -m pip list
          python -m pip show pynacl
