name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10.0-beta - 3.10'
          - 'pypy-3.7'
        os:
          # Windows Server 2019
          - windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}

      - name: Update pip
        run: python -m pip install -U pip

      - name: Show Python version
        run: python --version

      - name: Print PATH
        run: Write-Host $Env:Path

      - name: Print PATHEXT
        run: Write-Host $Env:PathExt

      - name: Find make
        run: |
          (Get-Command make).Path
          (Get-Command diff).Path

      - name: Show make version
        run: make --version

      - name: Search make using Python code
        run: |
          python searchmake.py make
          python searchmake.py diff

      - name: Test shutil
        shell: python
        run: |
          import shutil

          shutil.which("make")
          shutil.which("diff")

      - name: Install PyNaCl
        run: python -m pip install pynacl

      - name: PyNaCl info
        run: |
          python -m pip list
          python -m pip show pynacl
